In [1]:
import pandas as pd
import numpy as np
import os
import json

In [3]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
import joblib

### Data loading

In [4]:
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns=data.feature_names)
df['target'] = data.target

In [5]:
print("Data Shape", df.shape)
df.head()

Data Shape (569, 31)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,0

### Data EDA & Processing

In [6]:
df.info

<bound method DataFrame.info of      mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840
1          20.57         17.77          132.90     1326.0          0.08474
2          19.69         21.25          130.00     1203.0          0.10960
3          11.42         20.38           77.58      386.1          0.14250
4          20.29         14.34          135.10     1297.0          0.10030
..           ...           ...             ...        ...              ...
564        21.56         22.39          142.00     1479.0          0.11100
565        20.13         28.25          131.20     1261.0          0.09780
566        16.60         28.08          108.30      858.1          0.08455
567        20.60         29.33          140.10     1265.0          0.11780
568         7.76         24.54           47.92      181.0          0.05263

     mean compactness  mean concavity  mean concave points  mean symmetry  \
0             0.27760         0.30010              0.14710         0.2419
1             0.07864         0.08690              0.07017         0.1812
2             0.15990         0.19740              0.12790         0.2069
3             0.28390         0.24140              0.10520         0.2597
4             0.13280         0.19800              0.10430         0.1809
..                ...             ...                  ...            ...
564           0.11590         0.24390              0.13890         0.1726
565           0.10340         0.14400              0.09791         0.1752
566           0.10230         0.09251              0.05302         0.1590
567           0.27700         0.35140              0.15200         0.2397
568           0.04362         0.00000              0.00000         0.1587

     mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                   0.07871  ...          17.33           184.60      2019.0
1                   0.05667  ...          23.41           158.80      1956.0
2                   0.05999  ...          25.53           152.50      1709.0
3                   0.09744  ...          26.50            98.87       567.7
4                   0.05883  ...          16.67           152.20      1575.0
..                      ...  ...            ...              ...         ...
564                 0.05623  ...          26.40           166.10      2027.0
565                 0.05533  ...          38.25           155.00      1731.0
566                 0.05648  ...          34.12           126.70      1124.0
567                 0.07016  ...          39.42           184.60      1821.0
568                 0.05884  ...          30.37            59.16       268.6

     worst smoothness  worst compactness  worst concavity  \
0             0.16220            0.66560           0.7119
1             0.12380            0.18660           0.2416
2             0.14440            0.42450           0.4504
3             0.20980            0.86630           0.6869
4             0.13740            0.20500           0.4000
..                ...                ...              ...
564           0.14100            0.21130           0.4107
565           0.11660            0.19220           0.3215
566           0.11390            0.30940           0.3403
567           0.16500            0.86810           0.9387
568           0.08996            0.06444           0.0000

     worst concave points  worst symmetry  worst fractal dimension  target
0                  0.2654          0.4601                  0.11890       0
1                  0.1860          0.2750                  0.08902       0
2                  0.2430          0.3613                  0.08758       0
3                  0.2575          0.6638                  0.17300       0
4                  0.1625          0.2364                  0.07678       0
..                    ...             ...                      ...     ...
564                0.2216          0.2060                  0.07115       0
565                0.1628          0.2572                  0.06637       0
566                0.1418          0.2218                  0.07820       0
567                0.2650          0.4087                  0.12400       0
568                0.0000          0.2871                  0.07039       1

[569 rows x 31 columns]>

- check data types
- check missing values
- check any discrepancy in data
- check any special values
- check for any duplicates

In [7]:
df.drop_duplicates().shape

(569, 31)

In [8]:
df.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
target                     0
dtype: int64

In [ ]:
for col in df.columns:
  if df[col].isnull().sum()>0:
    df[col].fillna(df[col].mean(), inplace=True)

#### Feature emnineering

In [9]:
df['mean_area_log'] = np.log1p(df['mean area']) #data transformation
df['radius_area_ratio'] = df['mean radius'] / (df['mean area'] + 1) #Ratio Interactive Feature Creation
z = (df['mean area'] - df['mean area'].mean()) / df['mean area'].std()
df['is_anomaly'] = z.apply(lambda x: 1 if abs(x) > 2 else 0) #Anamoly Detection Feature Creation

### test train split

In [12]:
X = df.drop(columns=['target'])
y = df['target']

In [16]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.2, random_state=42)

In [17]:
print((X_train.shape, X_test.shape, y_train.shape, y_test.shape))

((455, 33), (114, 33), (455,), (114,))

### Scaling (linear models mandatory, tree based optional)

In [18]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

### Model Iterations

In [19]:
os.makedirs("models", exist_ok=True)
os.makedirs("logs", exist_ok=True)

----buildingmodel 1 logistic regression -----

In [21]:
lr_model_v1 = LogisticRegression(max_iter=1000)
lr_model_v1.fit(X_train_scaled, y_train)

LogisticRegression(max_iter=1000)

In [23]:
results = {}
preds_lr_v1 = lr_model_v1.predict(X_test_scaled)
results['lr_v1'] = {
    "accuracy": accuracy_score(y_test, preds_lr_v1),
    "precision": precision_score(y_test, preds_lr_v1),
    "recall": recall_score(y_test, preds_lr_v1),
    "f1": f1_score(y_test, preds_lr_v1)
}
joblib.dump(lr_model_v1, "models/lr_model_v1.pkl")

['models/lr_model_v1.pkl']

------model2 logistic regression (with stronger regularization) ------------

In [24]:
lr_model_v2 = LogisticRegression(max_iter=1000, C=0.1)
lr_model_v2.fit(X_train_scaled, y_train)

preds_lr_v2 = lr_model_v2.predict(X_test_scaled)
results['lr_v2'] = {
    "accuracy": accuracy_score(y_test, preds_lr_v2),
    "precision": precision_score(y_test, preds_lr_v2),
    "recall": recall_score(y_test, preds_lr_v2),
    "f1": f1_score(y_test, preds_lr_v2)
}

joblib.dump(lr_model_v2, "models/lr_model_v2.pkl")

['models/lr_model_v2.pkl']

---- model3: Random forest (baseline)- -----

In [25]:
rf_model_v1 = RandomForestClassifier(n_estimators = 100, random_state=42)
rf_model_v1.fit(X_train_scaled, y_train)

preds_rf_v1 = rf_model_v1.predict(X_test)

results['rf_v1'] = {
    "accuracy": accuracy_score(y_test, preds_rf_v1),
    "precision": precision_score(y_test, preds_rf_v1),
    "recall": recall_score(y_test, preds_rf_v1),
    "f1": f1_score(y_test, preds_rf_v1)
}

joblib.dump(rf_model_v1, "models/rf_model_v1.pkl")

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but RandomForestClassifier was fitted without feature names
  warnings.warn(
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

['models/rf_model_v1.pkl']

In [27]:
rf_model_v2 = RandomForestClassifier(n_estimators=1, max_depth=2, random_state=42)
rf_model_v2.fit(X_train, y_train)
preds_rf_v2 = rf_model_v2.predict(X_test)
results['rf_v2'] = {
    "accuracy": accuracy_score(y_test, preds_rf_v2),
    "precision": precision_score(y_test, preds_rf_v2),
    "recall": recall_score(y_test, preds_rf_v2),
    "f1": f1_score(y_test, preds_rf_v2)
    }
joblib.dump(rf_model_v2, "models/rf_v2.pkl")

['models/rf_v2.pkl']

In [36]:
# Save scaler
joblib.dump(scaler, 'models/scaler.pkl')


# models should use the same scaling as well in prodution so scaler also is being saved as a pickle file

['models/scaler.pkl']

### Compare all models

In [28]:
print("\nMODEL COMPARISON:")
for model_name, metrics in results.items():
  print(model_name, metrics)

MODEL COMPARISON:
lr_v1 {'accuracy': 0.9736842105263158, 'precision': 0.9722222222222222, 'recall': 0.9859154929577465, 'f1': 0.9790209790209791}
lr_v2 {'accuracy': 0.9824561403508771, 'precision': 0.9726027397260274, 'recall': 1.0, 'f1': 0.9861111111111112}
rf_v1 {'accuracy': 0.37719298245614036, 'precision': 0.0, 'recall': 0.0, 'f1': 0.0}
rf_v2 {'accuracy': 0.956140350877193, 'precision': 0.9583333333333334, 'recall': 0.971830985915493, 'f1': 0.965034965034965}

In [30]:
with open('logs/results.json', 'w') as f:
  json.dump(results, f, indent=4)

### Prediction pipeline (Using best model)

In [34]:
def predict_pipeline(input_df):
  model = joblib.load("models/lr_model_v1.pkl")

  input_df['mean_area_log'] = np.log1p(input_df['mean area'])
  input_df['radius_area_ratio'] = input_df['mean radius'] / (input_df['mean area'] + 1)

  z = (input_df['mean area'] - input_df['mean area'].mean()) / input_df['mean area'].std()
  input_df['is_anomaly'] = z.apply(lambda x: 1 if abs(x) > 2 else 0)

  scaler = joblib.load("models/scaler.pkl")
  input_df = scaler.transform(input_df)


  preds = model.predict(input_df)
  return preds

In [37]:
sample = X_test.iloc[:5].copy()
preds = predict_pipeline(sample)
print("\nPredictions:",preds)

Predictions: [1 0 0 1 1]

### Retraining

Reasons:
- new/add-on data
- new algorithm
- new iteration

In [38]:
new_data = df.sample(frac=0.2, random_state=1) #new-add on
X_new = new_data.drop(columns=['target'])
y_new = new_data['target']

X_combined = pd.concat([X_train, X_new])
y_combined = pd.concat([y_train, y_new])

rf_model_retrained = RandomForestClassifier(n_estimators=300, random_state=42)
rf_model_retrained.fit(X_combined, y_combined)

preds_retrained = rf_model_retrained.predict(X_test)

retrained_metrics = {
    "accuracy": accuracy_score(y_test, preds_retrained),
    "precision": precision_score(y_test, preds_retrained),
    "recall": recall_score(y_test, preds_retrained),
    "f1": f1_score(y_test, preds_retrained) }

In [39]:
print("\nRetrained Model performance:")
print(retrained_metrics)

joblib.dump(rf_model_retrained, "models/rf_retrained.pkl")

Retrained Model performance:
{'accuracy': 0.9649122807017544, 'precision': 0.958904109589041, 'recall': 0.9859154929577465, 'f1': 0.9722222222222222}

['models/rf_retrained.pkl']

In [40]:
with open("logs/retrained_metrics.json", "w") as f:
  json.dump(retrained_metrics, f, indent=4)